#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f $PROXY $1 > $3; cd -
}

URL="https://github.com/processwire/site-beginner/archive/refs/heads/main.zip"
dl $URL /usr/local/src site-beginner.zip
