#!/bin/bash -e
# regenerate processwire secrets and mysql password

. /etc/default/inithooks

USER=www-data
WEBROOT=/var/www/processwire
CONF=$WEBROOT/site/config.php

updateconf() {
    SALT=$(mcookie)
    sed -i "s|^\$config->userAuthSalt = .*|\$config->userAuthSalt = '$SALT';|" $CONF
    SALT=$(mcookie)
    sed -i "s|^\$config->tableSalt = .*|\$config->tableSalt = '$SALT';|" $CONF
    
    sed -i "s|^\$config->dbPass = .*|\$config->dbPass = '$1';|" $CONF
}

PASSWORD=$(mcookie)
updateconf $PASSWORD
$INITHOOKS_PATH/bin/mysqlconf.py --user=processwire --pass="$PASSWORD"
